name: Kings Duty Tests

on: [push]

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 10.16
      uses: actions/setup-node@v1
      with:
        node-version: 10.16
    - name: npm install, build, and test
      run: |
        npm install --no-optional
        npm install @angular/cli
        ng test --watch false --browsers ChromeHeadless
